In [ ]:
#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [1]:
import numpy as np

In [ ]:
#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [19]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [21]:
array = np.zeros(10) 
array[4] = 1
print(array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [22]:
np.arange(10,49,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [ ]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 9 (★☆☆)
`hint: reshape`

In [32]:
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [36]:
lst = [1, 2, 0, 0, 4, 0]
nonzero_indices = []

for i in range(len(lst)):
    if lst[i] != 0:
        nonzero_indices.append(i)

print(nonzero_indices)

[0, 1, 4]


In [ ]:
#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [38]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [42]:
np.random.random((3,3,3))

array([[[0.76765511, 0.2054924 , 0.40184655],
        [0.18254151, 0.29873561, 0.05215492],
        [0.61753366, 0.86473481, 0.3604411 ]],

       [[0.91089929, 0.25112774, 0.76823895],
        [0.69433828, 0.3561172 , 0.01851593],
        [0.94096217, 0.72224741, 0.91346757]],

       [[0.3291242 , 0.87362351, 0.67479305],
        [0.33489498, 0.40860971, 0.28015478],
        [0.78390877, 0.43477619, 0.27697294]]])

In [ ]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`


In [51]:
a = np.random.random((10,10))
print(a)

[[0.43659079 0.11112009 0.47813006 0.28068312 0.90346824 0.25246023
  0.13680568 0.01949102 0.63295125 0.6480861 ]
 [0.8433896  0.47641845 0.68423869 0.43233764 0.22511827 0.78057718
  0.24457781 0.04334973 0.04588847 0.07537832]
 [0.62897127 0.68419077 0.35168735 0.07123743 0.84485234 0.74036341
  0.27199508 0.71733936 0.74189309 0.83893919]
 [0.25578226 0.67394995 0.38343472 0.65683312 0.89915686 0.24990136
  0.54893542 0.02175384 0.6876774  0.20919681]
 [0.6596206  0.62961217 0.60864309 0.9510913  0.37524866 0.75432921
  0.04796749 0.44665774 0.66247276 0.86994108]
 [0.79867096 0.0069252  0.25960237 0.76650662 0.28798536 0.19618019
  0.82763576 0.7706087  0.0927321  0.09979803]
 [0.59625385 0.64671516 0.8945451  0.4665105  0.73004632 0.76002903
  0.5760699  0.77885854 0.89477971 0.90517355]
 [0.2485477  0.36769877 0.54156335 0.85762211 0.15607115 0.66192932
  0.74182374 0.91827723 0.86942076 0.37787742]
 [0.35889907 0.30859862 0.57375419 0.69686725 0.0355399  0.53017975
  0.1454016 

In [53]:
x = a.min()
y = a.max()
print(x)
print(y)

0.006925203574011163
0.9510912970892181


In [ ]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [56]:
b = np.random.random(30)
print(b)

[0.00968324 0.45551388 0.23716201 0.35601852 0.11867369 0.5917596
 0.30784561 0.79245536 0.81379586 0.87238378 0.83735749 0.10201487
 0.85608207 0.32957018 0.11664894 0.56661847 0.47665228 0.79032615
 0.82053613 0.98468288 0.53044515 0.12513574 0.81182878 0.55241331
 0.18806935 0.63123808 0.93631906 0.29030675 0.2264065  0.94433292]


In [58]:
mean = b.mean()
print(mean)

0.5224092216808136


In [ ]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`


In [ ]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [63]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.62299948 0.14772326 0.54120223 0.3393936  0.48207183]
 [0.09985519 0.43063471 0.73030442 0.05673244 0.24682679]
 [0.09000021 0.4224843  0.88434396 0.61655871 0.1298684 ]
 [0.99982597 0.16507236 0.16240279 0.35287525 0.57121964]
 [0.54470593 0.25421631 0.67821162 0.03983568 0.12168325]]
After normalization:
[[0.60746843 0.11238403 0.5222621  0.31204266 0.46066731]
 [0.06252095 0.40708644 0.71924555 0.01760096 0.21561792]
 [0.05225524 0.39859634 0.87970502 0.60075923 0.09378503]
 [1.         0.13045619 0.12767536 0.32608618 0.55353055]
 [0.52591182 0.22331541 0.66498166 0.         0.08525875]]


In [ ]:
#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`


In [67]:
ar1 = [1,2,3]
ar2 = [4,5,6]
(np.intersect1d(ar1,ar2))

array([], dtype=int64)

In [ ]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [73]:
a= np.random.random(10)
print(a)

[0.07324577 0.39612697 0.07321169 0.18716338 0.56592661 0.06176257
 0.89307001 0.6477732  0.19183164 0.42420494]


In [74]:
a.sort()
print(a)

[0.06176257 0.07321169 0.07324577 0.18716338 0.19183164 0.39612697
 0.42420494 0.56592661 0.6477732  0.89307001]


In [ ]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`


In [81]:
r = np.random.random(10)
print(r)

[0.69156515 0.28772565 0.57601165 0.88838885 0.92239694 0.77251174
 0.59089969 0.08377969 0.14889559 0.84283978]


In [82]:
r[r.argmax(0)]
print(r)

[0.69156515 0.28772565 0.57601165 0.88838885 0.92239694 0.77251174
 0.59089969 0.08377969 0.14889559 0.84283978]


In [ ]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [83]:
a = np.random.rand(3, 4)
print(a)

[[0.94365643 0.33500907 0.60596114 0.90411589]
 [0.21727255 0.14198243 0.46321739 0.10142904]
 [0.5640818  0.23149137 0.12558543 0.40321335]]


In [84]:
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[ 0.2464708  -0.36217656 -0.0912245   0.20693026]
 [-0.0137028  -0.08899292  0.23224204 -0.12954631]
 [ 0.23298882 -0.09960162 -0.20550756  0.07212037]]


In [ ]:
#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [ ]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [86]:
x = np.random.rand(5,3)
print(x)

[[0.67796129 0.05469228 0.06701323]
 [0.69067701 0.29743758 0.54682803]
 [0.32783451 0.96736007 0.06387344]
 [0.81453383 0.52818134 0.14106037]
 [0.94114154 0.59647308 0.95055717]]


In [89]:
y = x[x > 4] = x[x > 4] ** 2
print(y)

[]
